Fix low priority validation race condition.
formium/formik pull request #2854
Opened 2020-11-03 10:54 UTC by umidbekkarimov

2020-11-04 20:56 UTC, jaredpalmer commented
I think this looks good.

2020-11-04 21:01 UTC, jaredpalmer requested changes
See comment above.

2020-11-05 08:26 UTC, umidbekkarimov commented on packages/formik/src/Formik.tsx
> +        // anymore.
@jaredpalmer I did my best, please add suggestions if you have any.

2020-11-05 08:28 UTC, umidbekkarimov commented on packages/formik/src/Formik.tsx
> +        // anymore.
@jaredpalmer I did my best, please add suggestions if you have any.

2020-11-05 16:36 UTC, jaredpalmer approved these changes

2020-11-05 16:36 UTC, jaredpalmer commented
Thanks for this!

2020-11-05 16:38 UTC, merged

2020-11-05 17:39 UTC, Krasnopir commented
After update to 2.2.2 the form became strange. On the authorization form, I select a value from the suggested autocomplete in the input field, and the password field is automatically filled in. But the submit button does not become active, because the login field is in focus and the form is not marked as valid. After clicking outside the form, the password field is highlighted in error, despite the fact that it is filled, and only then the errors disappear and the form becomes valid.
So I back to 2.2.0.

2020-11-05 19:48 UTC, umidbekkarimov commented
> After update to 2.2.2 the form became strange. On the authorization form, I select a value from the suggested autocomplete in the input field, and the password field is automatically filled in. But the submit button does not become active, because the login field is in focus and the form is not marked as valid. After clicking outside the form, the password field is highlighted in error, despite the fact that it is filled, and only then the errors disappear and the form becomes valid.
> So I back to 2.2.0.
> 
> ```
>   const validationSchema = yup.object().shape({
>     email: yup
>       .string()
>       .email(t`Введите корректный email`)
>       .required(t`Обязательное поле`),
>     password: yup.string().required(t`Обязательное поле`),
>   });
> 
>   const formikConfig = {
>     validationSchema,
>     validateOnMount: true,
>     initialValues: {
>       email: '',
>       password: '',
>     },
>     onSubmit: handleLogin,
>   };
> ```

Fixed in https://github.com/formium/formik/pull/2865